version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      # 11 am PST
      time: "11:00"
      # PST timezone
      timezone: "America/Los_Angeles"
    rebase-strategy: "auto"
    commit-message:
      # Prefix all commit messages with "npm"
      # include a list of updated dependencies
      prefix: "npm"
      include: "scope"
    allow: 
      - dependency-name: "@polkadot/api"
      - dependency-name: "@polkadot/apps-config"
      - dependency-name: "@polkadot/util-crypto"
    ignore:
      - dependency-name: "confmgr"
      - dependency-name: "express"
      - dependency-name: "express-winston"
      - dependency-name: "http-errors"
      - dependency-name: "winston"
    labels:
      - "dependencies"
